services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=myuser
      - CLICKHOUSE_PASSWORD=my_password  
      - CLICKHOUSE_DATABASE=default
      - SECRET_KEY=my-secret-key
    volumes:
      - ./app:/app/app

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=myuser
      - CLICKHOUSE_PASSWORD=my_password
      - CLICKHOUSE_DATABASE=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/users.d/config.xml  # Gắn file cấu hình
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1", "--user", "myuser", "--password", "my_password"]  
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse-data: